name: movie_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  intl: ^0.18.0
  equatable: ^2.0.5
  retrofit: ^3.3.1
  dio: ^4.0.6
  build_runner: ^2.3.3
  provider: ^6.0.5
  retrofit_generator: ^4.0.1
  auto_route: ^5.0.1
  flutter_bloc: ^8.1.1
  pull_to_refresh: ^2.0.0
  path_provider: ^2.0.11
  hive: ^2.2.3
  shared_preferences: ^2.1.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  carousel_slider: ^4.1.1
  get_it: ^7.2.0
  alice: ^0.3.2
  flutter_screenutil: ^5.6.1
  awesome_dialog: ^3.0.2
  connectivity_plus: ^3.0.2
  permission_handler: ^10.2.0
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^3.2.0
  package_info_plus: ^3.0.2
  keyboard_dismisser: ^3.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  auto_route_generator: ^5.0.2
  hive_generator:
    git:
      url: https://github.com/yura2000/hive.git
      ref: master
      path: hive_generator/
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

flutter_intl:
  enabled: true